### ISSUE TITLE
PHP notice about GFCommon::decrypt() is deprecated since version 2.3!

### ISSUE THREAD

**Issue by galieth** [katzwebservices/Gravity-Forms-Constant-Contact-Add-on#15]
After upgrading Gravity forms I receive this message 4 times when I go the the add-on setting page

> Notice: GFCommon::decrypt() is deprecated since version 2.3! Use GFCommon::openssl_decrypt() instead. in /var/www/public_html/wp-includes/functions.php on line 3839

This notice also is output to the page when the form is submitted.

**Comment by galieth** [comment]
I should note running on apache with php 7

**Comment by zackkatz** [comment]
Pleas re-save your settings and that should fix it. Let me know if not.

**Comment by zackkatz** [comment]
(Your GF Constant Contact settings)

**Comment by magicspon** [comment]
Possibly a dumb question... but where is the GF Constant Contact settings?
