### ISSUE TITLE
State/Country Name Fields won't send.

### ISSUE THREAD

**Issue by NikV** [katzwebservices/Gravity-Forms-Constant-Contact-Add-on#6]
This looks like a change in the Constant Contact API where the fields for a contact simply don't exist anymore. I will look into making the changes and will submit a PR hopefully very soon!

**Comment by NikV** [comment]
Looked a little bit closer, it's just a matter of changing "StateName" to simply "State"

**Comment by NikV** [comment]
Unfortunately, that was not the cure for this. Seems like the current SDK is deprecated and may need to be adjusted a little bit to have "State" work.

**Comment by realfoodmobile** [comment]
Hi NikV
Any luck with this change? I am trying to make this work at the moment and the state name and country name fields still don't pass the data to constant contact. Thanks for your time.

**Comment by realfoodmobile** [comment]
I found that when I use the two letter country code for the value it works. this is based on their api documentation here: https://developer.constantcontact.com/docs/contacts-api/contacts-collection.html?method=POST

**Comment by zackkatz** [comment]
This has been fixed in Version 3.0 #10
